version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_tripulaciones
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3308:${MYSQL_PORT}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
      
  node:
    build: .
    container_name: node_tripulaciones
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules