version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_tripulaciones
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - moodly_api
    restart: always
      
  node:
    build: .
    container_name: node_tripulaciones
    ports:
      - ${APP_LOCAL_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - moodly_api
      - proxy
    environment:
      - VIRTUAL_HOST=moodlyapi.basurto.dev
      - LETSENCRYPT_HOST=moodlyapi.basurto.dev
      - LETSENCRYPT_EMAIL=admin@basurto.dev
    restart: always

  networks:
    proxy:
       name: nginx-proxy
       external: true
    moodly_api:
       name: moodly_api