-- MySQL Script generated by MySQL Workbench
-- lun 08 ene 2024 13:38:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tripulaciones` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tripulaciones` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tripulaciones` ;

-- -----------------------------------------------------
-- Table `tripulaciones`.`tbTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbTags` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;

USE `tripulaciones` ;

-- -----------------------------------------------------
-- Table `tripulaciones`.`tbCompanies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbCompanies` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `CIF` VARCHAR(10) NOT NULL,
  `displayName` VARCHAR(100) NOT NULL,
  `razonSocial` VARCHAR(100) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `CIF_UNIQUE` (`CIF` ASC) VISIBLE,
  UNIQUE INDEX `razonSocial_UNIQUE` (`razonSocial` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbBranches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbBranches` (
  `idBranch` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idBranch`),
  INDEX `fk_tbBranches_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbBranches_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbDepartments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbDepartments` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idDepartment`),
  INDEX `fk_tbDepartments_tbCompanies_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbDepartments_tbCompanies`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbShifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbShifts` (
  `idShift` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idShift`),
  INDEX `fk_tbShifts_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbShifts_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbEmployees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbEmployees` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `idDepartment` INT NULL DEFAULT NULL,
  `idBranch` INT NULL DEFAULT NULL,
  `idShift` INT NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `workerId` VARCHAR(15) NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  `passwordHash` VARCHAR(100) NULL DEFAULT NULL,
  `companyAdministrator` TINYINT NOT NULL,
  `superAdministrator` TINYINT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC) VISIBLE,
  UNIQUE INDEX `company_worker_UNIQUE` (`idCompany`, `workerId`) VISIBLE,
  INDEX `fk_tbEmployees_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbDepartments1_idx` (`idDepartment` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbBranches1_idx` (`idBranch` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbShifts1_idx` (`idShift` ASC) VISIBLE,
  CONSTRAINT `fk_tbEmployees_tbBranches1`
    FOREIGN KEY (`idBranch`)
    REFERENCES `tripulaciones`.`tbBranches` (`idBranch`),
  CONSTRAINT `fk_tbEmployees_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`),
  CONSTRAINT `fk_tbEmployees_tbDepartments1`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `tripulaciones`.`tbDepartments` (`idDepartment`),
  CONSTRAINT `fk_tbEmployees_tbShifts1`
    FOREIGN KEY (`idShift`)
    REFERENCES `tripulaciones`.`tbShifts` (`idShift`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `tripulaciones`.`tbComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbComments` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `idEmployee` INT NULL DEFAULT NULL,
  `idCompany` INT NOT NULL,
  `comment` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `idTag` INT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_tbReports_tbEmployees_idx` (`idEmployee` ASC) VISIBLE,
  INDEX `fk_tbReports_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  INDEX `fk_tbComments_tbTags1_idx` (`idTag` ASC) VISIBLE,
  CONSTRAINT `fk_tbReports_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`),
  CONSTRAINT `fk_tbReports_tbEmployees`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `tripulaciones`.`tbEmployees` (`idEmployee`),
  CONSTRAINT `fk_tbComments_tbTags1`
    FOREIGN KEY (`idTag`)
    REFERENCES `tripulaciones`.`tbTags` (`idTag`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbFeelings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbFeelings` (
  `idFeeling` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idFeeling`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbReasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbReasons` (
  `idReason` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idReason`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbScores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbScores` (
  `idScore` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idScore`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbVoting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbVoting` (
  `idVoting` INT NOT NULL AUTO_INCREMENT,
  `idEmployee` INT NOT NULL,
  `idCompany` INT NOT NULL,
  `previousDay` DATE NOT NULL,
  `previousDayScore` INT NOT NULL,
  `currentDay` DATE NOT NULL,
  `currentDayScore` INT NOT NULL,
  PRIMARY KEY (`idVoting`),
  INDEX `fk_tbVoting_tbEmployees1_idx` (`idEmployee` ASC) VISIBLE,
  INDEX `fk_tbVoting_tbScores1_idx` (`previousDayScore` ASC) VISIBLE,
  INDEX `fk_tbVoting_tbScores2_idx` (`currentDayScore` ASC) VISIBLE,
  INDEX `fk_tbVoting_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbVoting_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`),
  CONSTRAINT `fk_tbVoting_tbEmployees1`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `tripulaciones`.`tbEmployees` (`idEmployee`),
  CONSTRAINT `fk_tbVoting_tbScores1`
    FOREIGN KEY (`previousDayScore`)
    REFERENCES `tripulaciones`.`tbScores` (`idScore`),
  CONSTRAINT `fk_tbVoting_tbScores2`
    FOREIGN KEY (`currentDayScore`)
    REFERENCES `tripulaciones`.`tbScores` (`idScore`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbVotingFeelings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbVotingFeelings` (
  `idVotingFeelings` INT NOT NULL AUTO_INCREMENT,
  `idFeeling` INT NOT NULL,
  `idVoting` INT NOT NULL,
  PRIMARY KEY (`idVotingFeelings`),
  INDEX `fk_tbVotingFeelings_tbFeelings1_idx` (`idFeeling` ASC) VISIBLE,
  INDEX `fk_tbVotingFeelings_tbVoting1_idx` (`idVoting` ASC) VISIBLE,
  CONSTRAINT `fk_tbVotingFeelings_tbFeelings1`
    FOREIGN KEY (`idFeeling`)
    REFERENCES `tripulaciones`.`tbFeelings` (`idFeeling`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tbVotingFeelings_tbVoting1`
    FOREIGN KEY (`idVoting`)
    REFERENCES `tripulaciones`.`tbVoting` (`idVoting`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbVotingReasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbVotingReasons` (
  `idVotingReasons` INT NOT NULL AUTO_INCREMENT,
  `idVoting` INT NOT NULL,
  `idReason` INT NOT NULL,
  PRIMARY KEY (`idVotingReasons`),
  INDEX `fk_tbVotingReasons_tbVoting_idx` (`idVoting` ASC) VISIBLE,
  INDEX `fk_tbVotingReasons_tbReasons1_idx` (`idReason` ASC) VISIBLE,
  CONSTRAINT `fk_tbVotingReasons_tbReasons1`
    FOREIGN KEY (`idReason`)
    REFERENCES `tripulaciones`.`tbReasons` (`idReason`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tbVotingReasons_tbVoting`
    FOREIGN KEY (`idVoting`)
    REFERENCES `tripulaciones`.`tbVoting` (`idVoting`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `tripulaciones`;

DELIMITER $$
USE `tripulaciones`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `tripulaciones`.`tbEmployees_BEFORE_INSERT`
BEFORE INSERT ON `tripulaciones`.`tbEmployees`
FOR EACH ROW
BEGIN
	DECLARE empresa_departamento INT;
    DECLARE empresa_sede INT;
    DECLARE empresa_turno INT;
    
	-- Obtener la empresa del departamento, sede y turno a asignar
    IF NEW.idDepartment IS NOT NULL THEN
        SELECT idCompany INTO empresa_departamento FROM tripulaciones.tbDepartments WHERE idDepartment = NEW.idDepartment;
        IF NEW.idCompany != empresa_departamento THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El departamento no corresponde a la empresa del empleado.';
        END IF;
    END IF;

    IF NEW.idBranch IS NOT NULL THEN
        SELECT idCompany INTO empresa_sede FROM tripulaciones.tbBranches WHERE idBranch = NEW.idBranch;
        IF NEW.idCompany != empresa_sede THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La sede no corresponde a la empresa del empleado.';
        END IF;
    END IF;

    IF NEW.idShift IS NOT NULL THEN
        SELECT idCompany INTO empresa_turno FROM tripulaciones.tbShifts WHERE idShift = NEW.idShift;
        IF NEW.idCompany != empresa_turno THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El turno no corresponde a la empresa del empleado.';
        END IF;
    END IF;
    
END$$

USE `tripulaciones`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `tripulaciones`.`tbEmployees_BEFORE_UPDATE`
BEFORE UPDATE ON `tripulaciones`.`tbEmployees`
FOR EACH ROW
BEGIN
	DECLARE empresa_departamento INT;
    DECLARE empresa_sede INT;
    DECLARE empresa_turno INT;
    
	-- Obtener la empresa del departamento, sede y turno a asignar
    IF NEW.idDepartment IS NOT NULL THEN
        SELECT idCompany INTO empresa_departamento FROM tripulaciones.tbDepartments WHERE idDepartment = NEW.idDepartment;
        IF NEW.idCompany != empresa_departamento THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El departamento no corresponde a la empresa del empleado.';
        END IF;
    END IF;

    IF NEW.idBranch IS NOT NULL THEN
        SELECT idCompany INTO empresa_sede FROM tripulaciones.tbBranches WHERE idBranch = NEW.idBranch;
        IF NEW.idCompany != empresa_sede THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La sede no corresponde a la empresa del empleado.';
        END IF;
    END IF;

    IF NEW.idShift IS NOT NULL THEN
        SELECT idCompany INTO empresa_turno FROM tripulaciones.tbShifts WHERE idShift = NEW.idShift;
        IF NEW.idCompany != empresa_turno THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El turno no corresponde a la empresa del empleado.';
        END IF;
    END IF;
    
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
