-- MySQL Script generated by MySQL Workbench
-- jue 28 dic 2023 19:12:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tripulaciones` ;
-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tripulaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tripulaciones` ;
USE `tripulaciones` ;
USE `tripulaciones` ;

-- -----------------------------------------------------
-- Table `tripulaciones`.`tbCompanies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbCompanies` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `CIF` VARCHAR(10) NOT NULL,
  `displayName` VARCHAR(100) NOT NULL,
  `razonSocial` VARCHAR(100) NOT NULL,
  `horarioEntrada` TIME NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `CIF_UNIQUE` (`CIF` ASC) VISIBLE,
  UNIQUE INDEX `razonSocial_UNIQUE` (`razonSocial` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbBranchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbBranchs` (
  `idBranch` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `code` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idBranch`),
  INDEX `fk_tbBranchs_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbBranchs_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbDepartments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbDepartments` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idDepartment`),
  INDEX `fk_tbDepartments_tbCompanies_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbDepartments_tbCompanies`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbShifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbShifts` (
  `idShift` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `horarioEntrada` TIME NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idShift`),
  INDEX `fk_tbShifts_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_tbShifts_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbEmployees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbEmployees` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `idCompany` INT NOT NULL,
  `idDepartment` INT NULL DEFAULT NULL,
  `idBranch` INT NULL DEFAULT NULL,
  `idShift` INT NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  `passwordHash` VARCHAR(100) NULL DEFAULT NULL,
  `companyAdministrator` TINYINT NOT NULL,
  `superAdministrator` TINYINT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbCompanies1_idx` (`idCompany` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbDepartments1_idx` (`idDepartment` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbBranchs1_idx` (`idBranch` ASC) VISIBLE,
  INDEX `fk_tbEmployees_tbShifts1_idx` (`idShift` ASC) VISIBLE,
  CONSTRAINT `fk_tbEmployees_tbBranchs1`
    FOREIGN KEY (`idBranch`)
    REFERENCES `tripulaciones`.`tbBranchs` (`idBranch`),
  CONSTRAINT `fk_tbEmployees_tbCompanies1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `tripulaciones`.`tbCompanies` (`idCompany`),
  CONSTRAINT `fk_tbEmployees_tbDepartments1`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `tripulaciones`.`tbDepartments` (`idDepartment`),
  CONSTRAINT `fk_tbEmployees_tbShifts1`
    FOREIGN KEY (`idShift`)
    REFERENCES `tripulaciones`.`tbShifts` (`idShift`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbTags` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbVoting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbVoting` (
  `idVoting` INT NOT NULL AUTO_INCREMENT,
  `tbEmployees_idEmployee` INT NOT NULL,
  `entry` TINYINT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`idVoting`),
  INDEX `fk_tbVoting_tbEmployees1_idx` (`tbEmployees_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_tbVoting_tbEmployees1`
    FOREIGN KEY (`tbEmployees_idEmployee`)
    REFERENCES `tripulaciones`.`tbEmployees` (`idEmployee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tripulaciones`.`tbVotingTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tripulaciones`.`tbVotingTags` (
  `idVotingTags` INT NOT NULL AUTO_INCREMENT,
  `idVoting` INT NOT NULL,
  `idTag` INT NOT NULL,
  PRIMARY KEY (`idVotingTags`),
  INDEX `fk_tbVotingTags_tbVoting1_idx` (`idVoting` ASC) VISIBLE,
  INDEX `fk_tbVotingTags_tbTags1_idx` (`idTag` ASC) VISIBLE,
  CONSTRAINT `fk_tbVotingTags_tbTags1`
    FOREIGN KEY (`idTag`)
    REFERENCES `tripulaciones`.`tbTags` (`idTag`),
  CONSTRAINT `fk_tbVotingTags_tbVoting1`
    FOREIGN KEY (`idVoting`)
    REFERENCES `tripulaciones`.`tbVoting` (`idVoting`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
